/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CimPlatform: typeof import('./src/components/CimPlatform.vue')['default']
    CommunityManagement: typeof import('./src/components/CommunityManagement.vue')['default']
    EChartsWrapper: typeof import('./src/components/EChartsWrapper.vue')['default']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    EnergyDetection: typeof import('./src/components/EnergyDetection.vue')['default']
    EnergySavingAnalysis: typeof import('./src/components/EnergySavingAnalysis.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecurityMonitoring: typeof import('./src/components/SecurityMonitoring.vue')['default']
  }
}
